// auto-generated code, do not modify
package appkit

import "github.com/hsiafan/cocoa/ffi"

func init() {
	ffi.RegisterProtocol("appkit.AlertDelegate", ffi.ProtocolInfo{Name: "NSAlertDelegate"})
	ffi.RegisterProtocol("appkit.AnimationDelegate", ffi.ProtocolInfo{Name: "NSAnimationDelegate"})
	ffi.RegisterProtocol("appkit.AppearanceCustomization", ffi.ProtocolInfo{Name: "NSAppearanceCustomization"})
	ffi.RegisterProtocol("appkit.ApplicationDelegate", ffi.ProtocolInfo{Name: "NSApplicationDelegate"})
	ffi.RegisterProtocol("appkit.BrowserDelegate", ffi.ProtocolInfo{Name: "NSBrowserDelegate"})
	ffi.RegisterProtocol("appkit.CandidateListTouchBarItemDelegate", ffi.ProtocolInfo{Name: "NSCandidateListTouchBarItemDelegate"})
	ffi.RegisterProtocol("appkit.CollectionViewDataSource", ffi.ProtocolInfo{Name: "NSCollectionViewDataSource"})
	ffi.RegisterProtocol("appkit.CollectionViewDelegate", ffi.ProtocolInfo{Name: "NSCollectionViewDelegate"})
	ffi.RegisterProtocol("appkit.CollectionViewDelegateFlowLayout", ffi.ProtocolInfo{Name: "NSCollectionViewDelegateFlowLayout"})
	ffi.RegisterProtocol("appkit.CollectionViewElement", ffi.ProtocolInfo{Name: "NSCollectionViewElement"})
	ffi.RegisterProtocol("appkit.CollectionViewPrefetching", ffi.ProtocolInfo{Name: "NSCollectionViewPrefetching"})
	ffi.RegisterProtocol("appkit.CollectionViewSectionHeaderView", ffi.ProtocolInfo{Name: "NSCollectionViewSectionHeaderView"})
	ffi.RegisterProtocol("appkit.ComboBoxDataSource", ffi.ProtocolInfo{Name: "NSComboBoxDataSource"})
	ffi.RegisterProtocol("appkit.ComboBoxDelegate", ffi.ProtocolInfo{Name: "NSComboBoxDelegate"})
	ffi.RegisterProtocol("appkit.ControlTextEditingDelegate", ffi.ProtocolInfo{Name: "NSControlTextEditingDelegate"})
	ffi.RegisterProtocol("appkit.DatePickerCellDelegate", ffi.ProtocolInfo{Name: "NSDatePickerCellDelegate"})
	ffi.RegisterProtocol("appkit.DraggingDestination", ffi.ProtocolInfo{Name: "NSDraggingDestination"})
	ffi.RegisterProtocol("appkit.DraggingInfo", ffi.ProtocolInfo{Name: "NSDraggingInfo"})
	ffi.RegisterProtocol("appkit.DraggingSource", ffi.ProtocolInfo{Name: "NSDraggingSource"})
	ffi.RegisterProtocol("appkit.Editor", ffi.ProtocolInfo{Name: "NSEditor"})
	ffi.RegisterProtocol("appkit.FontChanging", ffi.ProtocolInfo{Name: "NSFontChanging"})
	ffi.RegisterProtocol("appkit.GestureRecognizerDelegate", ffi.ProtocolInfo{Name: "NSGestureRecognizerDelegate"})
	ffi.RegisterProtocol("appkit.ImageDelegate", ffi.ProtocolInfo{Name: "NSImageDelegate"})
	ffi.RegisterProtocol("appkit.LayoutManagerDelegate", ffi.ProtocolInfo{Name: "NSLayoutManagerDelegate"})
	ffi.RegisterProtocol("appkit.MatrixDelegate", ffi.ProtocolInfo{Name: "NSMatrixDelegate"})
	ffi.RegisterProtocol("appkit.MenuDelegate", ffi.ProtocolInfo{Name: "NSMenuDelegate"})
	ffi.RegisterProtocol("appkit.OutlineViewDataSource", ffi.ProtocolInfo{Name: "NSOutlineViewDataSource"})
	ffi.RegisterProtocol("appkit.OutlineViewDelegate", ffi.ProtocolInfo{Name: "NSOutlineViewDelegate"})
	ffi.RegisterProtocol("appkit.PasteboardItemDataProvider", ffi.ProtocolInfo{Name: "NSPasteboardItemDataProvider"})
	ffi.RegisterProtocol("appkit.PasteboardWriting", ffi.ProtocolInfo{Name: "NSPasteboardWriting"})
	ffi.RegisterProtocol("appkit.PathCellDelegate", ffi.ProtocolInfo{Name: "NSPathCellDelegate"})
	ffi.RegisterProtocol("appkit.PathControlDelegate", ffi.ProtocolInfo{Name: "NSPathControlDelegate"})
	ffi.RegisterProtocol("appkit.PopoverDelegate", ffi.ProtocolInfo{Name: "NSPopoverDelegate"})
	ffi.RegisterProtocol("appkit.RuleEditorDelegate", ffi.ProtocolInfo{Name: "NSRuleEditorDelegate"})
	ffi.RegisterProtocol("appkit.SearchFieldDelegate", ffi.ProtocolInfo{Name: "NSSearchFieldDelegate"})
	ffi.RegisterProtocol("appkit.SharingServiceDelegate", ffi.ProtocolInfo{Name: "NSSharingServiceDelegate"})
	ffi.RegisterProtocol("appkit.SharingServicePickerDelegate", ffi.ProtocolInfo{Name: "NSSharingServicePickerDelegate"})
	ffi.RegisterProtocol("appkit.SoundDelegate", ffi.ProtocolInfo{Name: "NSSoundDelegate"})
	ffi.RegisterProtocol("appkit.SplitViewDelegate", ffi.ProtocolInfo{Name: "NSSplitViewDelegate"})
	ffi.RegisterProtocol("appkit.TabViewDelegate", ffi.ProtocolInfo{Name: "NSTabViewDelegate"})
	ffi.RegisterProtocol("appkit.TableViewDataSource", ffi.ProtocolInfo{Name: "NSTableViewDataSource"})
	ffi.RegisterProtocol("appkit.TableViewDelegate", ffi.ProtocolInfo{Name: "NSTableViewDelegate"})
	ffi.RegisterProtocol("appkit.TextDelegate", ffi.ProtocolInfo{Name: "NSTextDelegate"})
	ffi.RegisterProtocol("appkit.TextFieldDelegate", ffi.ProtocolInfo{Name: "NSTextFieldDelegate"})
	ffi.RegisterProtocol("appkit.TextStorageDelegate", ffi.ProtocolInfo{Name: "NSTextStorageDelegate"})
	ffi.RegisterProtocol("appkit.TextViewDelegate", ffi.ProtocolInfo{Name: "NSTextViewDelegate"})
	ffi.RegisterProtocol("appkit.TokenFieldCellDelegate", ffi.ProtocolInfo{Name: "NSTokenFieldCellDelegate"})
	ffi.RegisterProtocol("appkit.TokenFieldDelegate", ffi.ProtocolInfo{Name: "NSTokenFieldDelegate"})
	ffi.RegisterProtocol("appkit.ToolbarDelegate", ffi.ProtocolInfo{Name: "NSToolbarDelegate"})
	ffi.RegisterProtocol("appkit.ToolbarItemValidation", ffi.ProtocolInfo{Name: "NSToolbarItemValidation"})
	ffi.RegisterProtocol("appkit.TouchBarDelegate", ffi.ProtocolInfo{Name: "NSTouchBarDelegate"})
	ffi.RegisterProtocol("appkit.UserInterfaceCompression", ffi.ProtocolInfo{Name: "NSUserInterfaceCompression"})
	ffi.RegisterProtocol("appkit.UserInterfaceItemIdentification", ffi.ProtocolInfo{Name: "NSUserInterfaceItemIdentification"})
	ffi.RegisterProtocol("appkit.ValidatedUserInterfaceItem", ffi.ProtocolInfo{Name: "NSValidatedUserInterfaceItem"})
	ffi.RegisterProtocol("appkit.ViewControllerPresentationAnimator", ffi.ProtocolInfo{Name: "NSViewControllerPresentationAnimator"})
	ffi.RegisterProtocol("appkit.ViewToolTipOwner", ffi.ProtocolInfo{Name: "NSViewToolTipOwner"})
	ffi.RegisterProtocol("appkit.WindowDelegate", ffi.ProtocolInfo{Name: "NSWindowDelegate"})
}
